### ISSUE TITLE
get wrong position of subToolbar list when I scrolling page

### ISSUE THREAD

**Issue by AmyShieh** [tinymce/tinymce-react#186] opened 2020-11-18 03:00 UTC
**What is the current behavior?**
   get the wrong position of sub toolbar list when I scrolling the page
**Please provide the steps to reproduce and if possible a minimal demo of the problem similar.**
![image](https://user-images.githubusercontent.com/18183021/99477073-bee87e00-298c-11eb-8334-32d912366151.png)
when I scrolled the page, I get some UI error like this:
![image](https://user-images.githubusercontent.com/18183021/99477245-12f36280-298d-11eb-81c8-1ec1856284cb.png)

I've set `ui-conatiner` and it still doesn't work.
``` jsx
<div id="tinymce_container_box" style={{position: 'relative'}}>
<Editor
                init={{
                    ui_container: '#tinymce_container_box',
                    minHeight: 0,
                    menubar: true,
                    plugins: [
                        'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                        'searchreplace wordcount visualblocks visualchars code fullscreen',
                        'insertdatetime media nonbreaking save table contextmenu directionality',
                        'paste textcolor colorpicker textpattern imagetools noneditable',
                        'autoresize'
                    ],
                    toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify',
            />

</div>

```

**What is the expected behavior?**
It should always get the correct position when I scroll the page.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

version: 3.6.0
browser: Chrome 86
OS: window 10

**Comment by tiny-james** [comment] 2020-11-18 04:23
Can you please provide a replication on [codesandbox](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14)?

I have been unable to replicate this problem. This was my attempt:
https://codesandbox.io/s/tinymcereact-forked-ckxf0?file=/src/index.js

**Comment by AmyShieh** [comment] 2020-11-18 09:52
> Can you please provide a replication on [codesandbox](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14)?
> 
> I have been unable to replicate this problem. This was my attempt:
> https://codesandbox.io/s/tinymcereact-forked-ckxf0?file=/src/index.js

I found the problem caused by the style of overflow, but I can't remove it, it seems can not be fixed.
![image](https://user-images.githubusercontent.com/18183021/99514528-d2b0d600-29c6-11eb-88ba-1a648fd4d42c.png)
https://codesandbox.io/s/tinymcereact-forked-q1ukc?file=/src/index.js

**Comment by tiny-james** [comment] 2020-11-19 02:23
Thanks for the bug report.

This is a known limitation of TinyMCE at the moment (see https://github.com/tinymce/tinymce/issues/5097 ).

The cause is that TinyMCE renders its menus and popup dialogs in a separate container at the end of the page. This is done because of layering issues (needing to appear on top of everything else) and to allow things like popups to fill the entire page and not be constrained by things like `overflow: hidden`.

The only current workaround is to move the container that contains the menus and popup dialogs into the same location as the editor but this has all the downsides listed above. If you wish to try this add this to your `init` prop:
```
setup: function(editor) {
  editor.on('PostRender', function() {
    var container = editor.getContainer();
    var uiContainer = document.querySelector('.tox.tox-tinymce-aux');
    container.parentNode.appendChild(uiContainer);
  });
}
```
See https://codesandbox.io/s/tinymcereact-forked-80mbh?file=/src/index.js as an example.

Because we can do nothing to fix this in the react integration I am closing this as a duplicate of the TinyMCE issue: https://github.com/tinymce/tinymce/issues/5097

**Closed by tiny-james** 2020-11-19 02:23 UTC
