### ISSUE TITLE
Editor on with FluentUI Panel component, lack of focus

### ISSUE THREAD

**Issue by sirdawidd** [tinymce/tinymce-react#412] opened 2022-11-24 15:19 UTC
I'm using latest version of tinymce-react and Fluent UI, when I try to put editor inside FuentUI component called Panel, any of options, like lists, are not working, only elements which are clickable. Seems like problem with focus. 
Does anyone try to use 
Editor on https://developer.microsoft.com/en-us/fluentui#/controls/web/panel  ?
Or to add z-index param on editor configuration 
`<div class="tox tox-silver-sink tox-tinymce-aux" style="width: 1068px;position: relative; z-index: 9999990;">`

**Comment by yacodes** [comment] 2022-12-12 19:09
@sirdawidd There is not enough info for us to start working on the issue. Also it seems that the problem can be with the Fluent UI.

I will close the issue. If you're sure that the problem is with `tinymce-react` integration, please open a new PR with a reproducible demo at codepen or a similar service.

**Closed by yacodes** 2022-12-12 19:09 UTC
Labels: GitHub
