### ISSUE TITLE
Table of Content Plugin doesn't works React-router

### ISSUE THREAD

**Issue by huyb1991** [tinymce/tinymce-react#224] opened 2021-02-17 09:10 UTC
I'm using react-router-dom v4, and app url is something like `http://domain.com/#/page1`

Then Table of Content is doesn't work with it, there 2 problem:
- Two `#` character on url, so, ToC will jump wrong section
- ToC update link incorrect.

Here's my example code:
```
<Editor
  apiKey={process.env.REACT_APP_TINY_API_KEY}
  init={{
    document_base_url: 'http://domain.com/#/page1',
    ... // other configs
  }}
/>
```

Then ToC link is `http://domain.com/#mcetoc_1eu2qlv9u18`. It's missing link current page or `props.location.pathname` of react-router-dom.

My package version:
```
"react-router-dom": "^4.4.0-beta.8",
"@tinymce/tinymce-react": "^3.7.0",

```

**Comment by tiny-james** [comment] 2021-02-18 07:26
As far as I can tell both the TOC plugin and the document_base_url are working as intended.

The TOC plugin does two things:
1. It finds headings and assigns ID attributes
2. Then it creates links to the ID using the fragment

It is completely unaware of the context that it is used in, so when the page in which the content is displayed uses the fragment with javascript the links will have to be rewritten.

Additionally the `document_base_url` can not have a fragment which is for a similar reason because there is no standard way to combine a URL and a base URL when the base URL has a fragment.

The only way that this could work is if you rewrite the URLs when the content is read into the editor and written out of the editor.

To rewrite the URLs you'll probably end up using attribute filters like this:
```tsx
<Editor
  init={{
    setup: (editor) => {
      editor.on('PostRender', () => {
        editor.parser.addAttributeFilter('src,href', (nodes, name) => {
          for (var i = 0; i < nodes.length; i++) {
            var url = node.attr(name);
            // convert the url to the internal format
            node.attr(name, url);
          }
        });
        editor.serializer.addAttributeFilter('src,href', (nodes, name) => {
          for (var i = 0; i < nodes.length; i++) {
            var url = node.attr(name);
            // convert the url to the external format
            node.attr(name, url);
          }
        });
      });
    }
  }}
/>
```
My googling suggests that you'll also need [react-router-hash-link](https://www.npmjs.com/package/react-router-hash-link) or some other mechanism for interpreting the URL and scrolling to the correct section of the page.

Good luck. I'm closing this issue because the component is working as intended.

**Closed by tiny-james** 2021-02-18 07:26 UTC
Labels: GitHub
