### ISSUE TITLE
create-react-app css

### ISSUE THREAD

**Issue by Ebuall** [tinymce/tinymce-react#168] opened 2020-09-09 08:39 UTC
Is there still no way to add css to an iframe from create-react-app build pipeline?

**Comment by Ebuall** [comment] 2020-09-09 11:32
Same goes for skins. We need to be able to import those.

**Comment by sirajalam049** [comment] 2020-09-09 21:16
Do you want a custom css for your editor content?

**Comment by Ebuall** [comment] 2020-09-10 06:45
I just need the same styling and fonts in the isolated iframe as outside. And to use it as a module without no-api-key thing.

**Comment by sirajalam049** [comment] 2020-09-10 11:37
You can't just add the css inside an iframe. But as far as I understand, you want to pass css to the editor (which is in iframe). You can inject a css file to the init props as shown below.
```
 <Editor
    init={{
    content_css: 'https://yourcustomcsscdn.css'
   ...
  ....
  }}
/>
```

Or it is something else you want, add more info exactly what you are trying to do and what you've tried. A couple of screenshots or codes will be helpful.

**Comment by Ebuall** [comment] 2020-09-11 06:24
> yourcustomcsscdn.css

That's what I'm talking about. In CRA we generate css automatically with hashes. And use imports only. You have an example with CRA in docs, but don't really support it.

**Comment by sirajalam049** [comment] 2020-09-11 13:55
Can you share exactly what part of the documentation that you're referring and not working for you?

**Comment by tiny-james** [comment] 2020-09-14 00:19
The `init` prop lets you pass anything you like to TinyMCE's init function so you can use the [content_style](https://www.tiny.cloud/docs/configure/content-appearance/#content_style) setting to pass raw CSS if you desire.
Same with skins, there's a [skin_url](https://www.tiny.cloud/docs/configure/editor-appearance/#skin_url) setting for that.

**Comment by Ebuall** [comment] 2020-09-14 06:17
There isn't a native way to get raw css or flat static url in CRA by default. There might be some way by hacking around webpack, but that is discouraged and against the CRA philosophy

**Comment by tiny-james** [comment] 2020-09-14 07:00
Well it's impossible for TinyMCE to support CRA's method of building perfectly as TinyMCE must create its own page dynamically in an IFrame. I suppose the closest you could get is using inline mode.

However CRA does have an escape hatch for these situations:
[https://create-react-app.dev/docs/using-the-public-folder](https://create-react-app.dev/docs/using-the-public-folder)

**Comment by Ebuall** [comment] 2020-09-14 08:36
I believe with CRA you have no problems doing code-splitting without the need for an IFrame. Having an option of a full modular consumption would be the best way to support modern frontend workflow.

Public folder has its own downsides, as it doesn't get processed, so links to fonts and css files become dead.

**Comment by sirajalam049** [comment] 2020-09-14 08:48
I did my job this way. Just added the css file to CDN and inject directly via props. You can create a [free CDN link for your CSS ](https://garbagevalue.com/blog/create-free-cdn-link). Hope it helps.

**Comment by tiny-james** [comment] 2020-09-28 06:44
I'm closing this issue because I can't see any way the integration can support this use case better. 

As stated previously TinyMCE in iFrame mode creates an internal page that does not inherit any styles from the surrounding page by design. If styles need to be passed into TinyMCE they can be passed as literal styles or by URLs to CSS, alternatively the editor can be loaded in inline mode where it runs on elements that are part of the page (and hence have the same styling).

**Closed by tiny-james** 2020-09-28 06:44 UTC
