### ISSUE TITLE
Internal pasting in mobile devices is considered external in paste_preprocess

### ISSUE THREAD

**Issue by ashwingattani** [tinymce/tinymce-react#411] opened 2022-11-24 10:12 UTC
**What is the current behavior?**
When pasting internally from tinyMCE editor on a mobile browser, the args in paste_preprocess gives args.internal as false.

As in the image, I am disabling the external paste option for the editor. This works well on desktop browsers, however, when I copy from the editor and try to paste back into the same editor, the args.internal return false.

<img width="1009" alt="Screenshot 2022-11-24 at 3 34 24 PM" src="https://user-images.githubusercontent.com/9816850/203755796-3e0fb062-f471-4f57-929e-43e7534e014c.png">

**What is the expected behavior?**
On copying from the editor, the paste should be termed as internal for mobile devices.

**Comment by yacodes** [comment] 2022-12-12 19:12
@ashwingattani Seems like this issue is related to the `tinymce` itself, not the `react` integration. 

I will close the issue due to it being non-related to this repo. Please open an issue in the original `tinymce` repository with a link to a reproducible demo on codepen or similar service.

**Closed by yacodes** 2022-12-12 19:12 UTC
Labels: GitHub
