### ISSUE TITLE
TinyMCE onContentSave event is fired on componentWillUnmount

### ISSUE THREAD

**Issue by brandonryan** [tinymce/tinymce-react#114] opened 2020-02-27 17:14 UTC
**What is the current behavior?**
When the tinymce component is unmounted, a save event is fired causing unexpected behavior.
This caused us a headache in production for our app. Took a while to track down.

[codesandbox.io](https://codesandbox.io/s/tinymcereact-wumpl)
_don't know why its getting a network error, you can close it and ignore then it works fine._

**What is the expected behavior?**
Editor should not save when it is unmounted unless explicitly told to by some property

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
@tinymce/tinymce-react@3.5.0
This is the only version ive used.

**Comment by SimonFc** [comment] 2020-02-28 08:15
Hmm I would have assumed that a lot of the save functionality TinyMCE provides doesn't makes sense when using tinymce-react since the target element (textarea or div depending on the mode) is created and handled by tinymce-react. What problem are you solving by listening to the `onContentSave` event?

**Comment by brandonryan** [comment] 2020-02-28 15:23
I'm listening to onContentSave so that I can save when the user presses the save button via the `save` toolbar plugin, I can send a request to the backend and write the value to the database. It caused an issue where we cleared out our data in our [redux](https://redux.js.org/) state tree then changed page, an empty string was saved to the backend.

**Comment by quoeradem** [comment] 2020-03-10 13:45
FWIW I've been able to reproduce the issue with multiple versions of **TinyMCE** and `tinymce-react`.

As a workaround, I am currently wrapping the `tinymce-react`component in a HOC and unbinding the `savecontent` event listener from the editor when the component is unmounted.

**Example:** https://codesandbox.io/s/tinymcereact-3yhrh

**Comment by brandonryan** [comment] 2020-03-10 14:55
Another workaround is wrapping the onSaveContent callback and checking `event.is_removing`

**Comment by tiny-james** [comment] 2020-05-07 00:16
This issue should now be fixed by https://github.com/tinymce/tinymce-react/pull/133

**Closed by tiny-james** 2020-05-07 00:16 UTC
Labels: bug, status: escalated
