### ISSUE TITLE
Tinymce error on resize window

### ISSUE THREAD

**Issue by dacopan** [tinymce/tinymce-react#146] opened 2020-06-18 15:44 UTC
**What is the current behavior?**
When tinymce is loaded as disabled then resize window and enable editor a strange error occur

**steps to reproduce**
link: [https://5oi3i.csb.app/](https://5oi3i.csb.app)
1. load in small size  900 for example
2. resize window to 1200
3. press toggle
4. press toggle

source code: https://codesandbox.io/s/tinymcereact-5oi3i?file=/src/index.js:0-1646

```
The component must be in a context to send: getByDom
<div aria-pressed="false" aria-label="Bullet list" title="Bullet list" role="button" aria-haspopup="true" unselectable="on" tabindex="-1" class="tox-split-button tox-tbtn--disabled" style="user-select: none;" aria-disabled="true" aria-expanded="false" aria-describedby="aria_2622540402021592495008207"></div> is not in context
```

**What is the expected behavior?**
Editor should permit enable/disable edit mode without errors

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
- TinyMCE react 3.6.0 same behavior on 3.5.0 not tested in more previous
- Ubuntu 20.04 Chrome 81.0.4044.122 and Firefox

**Comment by arcoro** [comment] 2020-06-18 15:49
same error please help

**Comment by dacopan** [comment] 2020-06-18 15:58
apparently the problem is here 
https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/themes/silver/main/ts/ui/toolbar/button/ToolbarButtons.ts#L286

**Comment by jscasca** [comment] 2020-07-03 01:23
I'm looking into this issue and trying to come with a workaround while I can find the root cause. It might be related to the reference of the editor not being attached to an actual element in the page after the re-rendering.

**Comment by tiny-james** [comment] 2020-09-09 00:17
I have replicated this in pure TinyMCE here:
[http://fiddle.tinymce.com/Vrhaab/2](http://fiddle.tinymce.com/Vrhaab/2)

An expert in TinyMCE's UI library looked into it and came up with this explanation:

-  the editor is resized via css. Nothing happens immediately.
-  the setMode('design') is called. This ends with a nodeChange.
-  the components listening to the nodeChange are identified by EventDispatcher. This includes the components that are about to be removed from the DOM because they no longer fit in the smaller toolbar
-  iframe's nodeChange listener fires, which calls resizeContent
-  iframe's resizeContent handler fires which calls refresh on the toolbar, and removes all the toolbar groups that don't fit in the new editor width. This also removes the nodeChange handlers from these components
-  the current nodeChange event keeps iterating through all the listeners identified up-front. Finds the toolbar buttons that were just removed. Tries to call their handlers and an error occurs.

There is now a ticket in the TinyMCE backlog to fix this issue with this explanation and a suggested fix. When that gets completed I will update this issue.

**Comment by kicsigabszi** [comment] 2020-11-27 06:36
Same here. Any solution?

**Comment by tiny-james** [comment] 2020-12-07 03:02
The bug fix is currently scheduled for TinyMCE 5.7 eta Mid Feb 2021.

Internal references: TINY-6383 , INT-2204

**Comment by tiny-james** [comment] 2021-02-15 07:56
This fix is now likely to be in TinyMCE 5.8 (it did not make 5.7).

**Comment by bjezyk** [comment] 2021-04-01 13:55
Same here. After resizing the browser window in inline mode or default view mode with added `defaultValue`, content of the editor disappears.

**Comment by tiny-james** [comment] 2021-05-12 00:05
Work has been completed upstream in the tinymce repository and will be released in 5.8.1.

- https://github.com/tinymce/tinymce/pull/6789
- https://github.com/tinymce/tinymce/pull/6807
- https://github.com/tinymce/tinymce/pull/6805

**Comment by tiny-james** [comment] 2021-05-20 02:41
TinyMCE community 5.8.1 has been released and contains a fix for this issue:
https://codesandbox.io/s/tinymcereact-issue-146-fixed-pf62u

The 5.8.1 release can currently be used on cloud with the `cloudChannel` prop set to `"5-testing"` barring any major bugs this will becomes the enterprise release in two weeks and will then be available on the default cloud channel `"5"`.

**Comment by tiny-james** [comment] 2021-05-26 02:58
TinyMCE enterprise 5.8.1 has been released and so this fix is now available on the default cloud channel "5".

Closing this issue as fixed.

**Closed by tiny-james** 2021-05-26 02:58 UTC
Labels: GitHub, bug, escalated
