### ISSUE TITLE
Table plugin bugs

### ISSUE THREAD

**Issue by sandorvasas** [tinymce/tinymce-react#126] opened 2020-04-24 16:11 UTC
TinyMCE 5.2.2
tinymce-react 3.5.0

When trying to insert a table, and the grid appears, I can only select a 1x1 table, the others are greyed out. Not sure if it doesn't recognize pointer events or what. If devtools are open and I go over the grid with 'Inspect Element', then it starts to recognize the cursor. So then if I turn off inspect element and start hovering the mouse above the grid, it works fine.
(Btw even tho it displays 1x1 and I can't select a larger table, if I DO select e.g. a 5x6 table, it will create a 5x6 table, so I reckon just the grid's UI is not updating well)

Other issue which is quite similar is that after inserting a table, selecting it, then clicking anything on the table toolbar does nothing but hide the toolbar.

**Comment by lnewson** [comment] 2020-04-26 05:33
Closing as a duplicate of https://github.com/tinymce/tinymce/issues/5606

**Closed by lnewson** 2020-04-26 05:33 UTC
