### ISSUE TITLE
value is invisible 

### ISSUE THREAD

**Issue by Deeptrentium** [tinymce/tinymce-react#295] opened 2021-11-15 06:59 UTC
**I am using this package with react-sortablejs and when I try to sort index via drag the value of the Editor box is invisible and when I use the console to show the value it shows me the value even if I refresh the page value again visible it's only happened when I sort the box via drag **

** here I show you how I used and call this library due to some security i do not give u the howl page so its maybe its show you some error but you can understand how I use that and what is the error https://codesandbox.io/s/epic-bogdan-ved61?file=/src/editer.js**

**if I change the index of the Editor box I still want to show my editor box value **

**I used 3.8.0 in its affected in every browser and also it's not work in previous version **

**Comment by tiny-james** [comment] 2021-11-17 03:35
I can't get the example you linked to run due to an error "t.list is undefined" from react-sortablejs.

Based on your description I suspect the problem is that TinyMCE can't be removed and re-added to the DOM as it is based on an iframe which looses its state when removed. There is more discussion about this problem here:
https://github.com/tinymce/tinymce-react/discussions/242

The two standard work-arounds are:
1. Initialize the editor when the field is focused for editing and when editing completes render as plain HTML.
2. Detect when the editor is about to be moved and store the editor content and current selection. Destroy the editor and use a placeholder for the move (ie the contained HTML). Once the move has completed then initialise a new editor with the stored content and selection.

**Comment by tiny-james** [comment] 2022-01-20 00:57
Closing as probably unsolvable due to TinyMCE using an Iframe to store state. 

The TinyMCE developers are aware of the problem but it a tricky one to solve as the iframe is the current source of truth for the editor value. In future (hopefully in TinyMCE 6) the iframe will become just a way of rendering the editor value and this will be solvable.

**Closed by tiny-james** 2022-01-20 00:57 UTC
Labels: GitHub
