### ISSUE TITLE
table border styles not applied correctly

### ISSUE THREAD

**Issue by dani-ttci** [tinymce/tinymce-react#415] opened 2022-12-01 05:11 UTC
**What is the current behavior? Describe the bug**
I am working on modifying table and it seems that border style are not being applied correctly, because this style is not being added on each cell. It actually works on this [demo page](https://www.tiny.cloud/tinymce/features/advanced-tables/) but not on this [demo page](https://codepen.io/pen)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
You can test [here](https://codepen.io/pen). 
To replicate, simply highlight a table and update table properties. Add a border style and color and click save.

**What is the expected behavior?**
It should display correctly like what is being shown [here](https://www.tiny.cloud/tinymce/features/advanced-tables/)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Im using react tinymce which uses tinymce v6

**Comment by yacodes** [comment] 2022-12-12 19:05
@dani-ttci Unfortunately the link to the codepen is broken. I couldn't reproduce the issue on my own. Please, attach a link to a minimal demo of the problem once more.

**Comment by tiny-james** [comment] 2023-01-05 08:00
Without a working example I can't do anything so I'm closing this as unreplicatable.

It's worth noting that this is highly unlikely to be caused by the tinymce-react integration but will be something to do with an interaction between your page CSS and tinymce itself. If you do manage to create a replication I suggest reporting it on the `tinymce` repository.

**Closed by tiny-james** 2023-01-05 08:00 UTC
Labels: needs: more info, GitHub

**Comment by mauricioprado00** [comment] 2025-02-13 14:19
solution in here:
https://github.com/tinymce/tinymce/pull/10160

please vote up so they push the fix:
https://github.com/tinymce/tinymce/discussions/10165
