### ISSUE TITLE
Support toolbar false

### ISSUE THREAD

**Issue by haxxxton** [tinymce/tinymce-react#260] opened 2021-05-12 11:48 UTC
**Is your feature request related to a problem? Please describe.**
Currently, tinymce-react treats the toolbar as a string only value https://www.tiny.cloud/docs/integrations/react/#toolbar. However, tinymce supports the option to provide a `false` option to remove the toolbar.

 **Describe the solution you'd like**
Ideally, tinymce-react supports the same functionality as tinymce's init option with regards to toolbar

 **Describe alternatives you've considered**
Currently, the only alternative is to provide the boolean option for toolbar inside the init object. If you need to toggle the toolbar on-the-fly, you need to change a 'key' prop on the Editor panel to force a reinit.

**Comment by tiny-james** [comment] 2021-05-13 00:29
>  alternative is to provide the boolean option for toolbar inside the init object.

Yep.

It was intended that the toolbar prop would work identically but it seems we have been bitten by falsy again:
```js
this.props.toolbar || (this.props.init && this.props.init.toolbar)
```

We should probably change that to:
```js
this.props.toolbar ?? (this.props.init && this.props.init.toolbar)
```

That said, fixing it will not make what you requested work:

> If you need to toggle the toolbar on-the-fly, you need to change a 'key' prop on the Editor panel to force a reinit.

Changing the toolbar after init is not supported by TinyMCE. The **only** way to change it is to re-init TinyMCE.

What you probably could do is hide the editor toolbar with CSS.
https://codesandbox.io/s/tinymcereact-toggle-toolbar-ne0xl

> You need to change a 'key' prop on the Editor panel to force a reinit.

That is the current recommended method yes. Forcing a re-init is generally something we want to avoid as it loses almost all editor state. We can pretty much only keep the content and the cursor position if we specifically save them first. Currently we can't even get the full undo state and we can't restore it afterwards anyway.

**Comment by haxxxton** [comment] 2021-05-13 22:58
@tiny-james thanks for the speedy reply! CSS does feel like the easier of the two options then, this is something im using in conjunction with disabling/readonly the input, so just hiding the toolbar sounds like a plan. While my particular usecase means its highly unlikely that someone is going to be flitting between no toolbar and having one, losing the undo state sounds pretty horribly UX if i were to do it.

Thanks again

**Comment by tiny-james** [comment] 2021-05-14 03:31
Closing as solved.

**Closed by tiny-james** 2021-05-14 03:31 UTC
Labels: GitHub
