### ISSUE TITLE
tinymce core types

### ISSUE THREAD

**Issue by cipacda** [tinymce/tinymce-react#153] opened 2020-07-31 12:25 UTC
**Is your feature request related to a problem? Please describe.**
This is a feature request: The types that come with `@tinymce/tinymce-react` only describe types for the react specific layer added, but not for the underlying tiny-mce library.

 **Describe the solution you'd like**
Ideally we'd add types the types for tinmyce (provided in `@types/tinymce`) to this solution as well. The ideal would be to replace the `init: Record<string, any>` definition we currently have with a actual types from ` @types/tinymce`.

**Comment by tiny-james** [comment] 2020-09-04 04:35
Hi cipacda,

We have plans to publish the official TinyMCE types soon (the 5.5 release I think but I may be wrong) so when that happens I'll use them in the react integration where I can. The problem is then that the types change subtlety between versions of TinyMCE and the react plugin allows you to pick what version you use so even then I'd like a way to allow the user to specify what types they use (not sure how to do that yet).

The types provided by the definitely typed project are also a little too restrictive as they do not allow defining custom settings for new plugins which must be supported.

**Comment by tiny-james** [comment] 2020-10-08 07:46
TinyMCE 5.5 has been released so I have created a PR to add the types.
https://github.com/tinymce/tinymce-react/pull/178

**Comment by tiny-james** [comment] 2020-10-14 00:10
The PR has been merged and tinymce-react 3.8.0 has been released. I'm closing this issue as complete.

**Closed by tiny-james** 2020-10-14 00:10 UTC
Labels: enhancement
