### ISSUE TITLE
Wrong cursor style when Editor is rendered into a modal

### ISSUE THREAD

**Issue by romseguy** [tinymce/tinymce-react#309] opened 2022-01-12 17:34 UTC
I'm rendering `Editor` into a chakra-ui `Modal`. When hovering the content edit area, cursor is `pointer` instead of `text`. Visually, I couldn't find any `cursor` css property anywhere when inspecting).

**Which versions of TinyMCE, and which browser / OS are affected by this issue?

tinymce 5.10.2
tinymce-react 3.13.0

Chrome 96
Chromium 94
Firefox 80

Did this work in previous versions of TinyMCE or `tinymce-react`?**

I don't know

**Comment by tiny-james** [comment] 2022-01-20 05:10
It seems to display a text cursor when I hover over text and an arrow when not over text.
https://codesandbox.io/s/tinymce-react-chakra-ui-modal-pu9o0
![Selection_071](https://user-images.githubusercontent.com/41130888/150277238-d3b7beda-5ebe-493e-97e7-a999ce64bfb2.png)


This seems identical to the behavior when not in the modal.

Please provide any additional details needed to replicate your issue.

**Comment by MMohesen88** [comment] 2022-02-27 19:27
I think the issue is CSS, i tried to fixe is by changing the ZIndex, but wouldn’t fix since I used the modal in the editor itself, as you can see in the screen shot below the editor in the modal and the` insert/edit link modal` inputs are disabled not editable thats is because the `[role="presentation"]` selector is z-index = 1300 and the position fixed

<img width="1792" alt="Screen Shot 2022-02-27 at 10 22 04 PM" src="https://user-images.githubusercontent.com/90827115/155896599-6012325d-7f03-4229-ab51-60dff5315242.png">

**Comment by tiny-james** [comment] 2022-06-22 02:00
I added `"@material-ui/core": "^4.12.4",` to the dependencies and imported it to the page and it didn't seem to make any difference.

Can you modify the replication case to demonstrate the problem:
https://codesandbox.io/s/tinymce-react-chakra-ui-modal-pu9o0?file=/src/index.js

Without a clear replication I can not help and I will close this issue.

**Comment by tiny-james** [comment] 2022-08-01 03:57
Closing as I cannot replicate this issue.

**Closed by tiny-james** 2022-08-01 03:57 UTC
Labels: needs: more info, GitHub
