### ISSUE TITLE
Text color plugin not working in spfx 1.8.2 with React 16+

### ISSUE THREAD

**Issue by suryarsp** [tinymce/tinymce-react#83] opened 2019-08-06 06:37 UTC
**Tinymce version: 4.7.6
tinymce/tinymce-react: 2.1.4**

I just created a new webpart in spfx with latest version of React.

` import * as  React from "react";
import { Editor } from "@tinymce/tinymce-react";
import { ITextEditorProps, ITextEditorState} from '../../../../interfaces';
export default class TextEditor extends React.Component<ITextEditorProps, ITextEditorState> {

     constructor(props) {
          super(props);
     }

     private editorConfig = {
          menubar: false,
          plugins: [
               'lists link anchor textcolor',
               'paste'
             ],
          paste_as_text: true,
          paste_text_sticky: true,
          paste_text_sticky_default: true,
          toolbar:
               " bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | forecolor backcolor",
          branding: false,
          statusBar: false,
          content_style:
               ".mce-content-body {font-size: " + this.props.defaultFontSize + "px; font-family:" + this.props.defaultFontFamily + ";}",
     };

     public render() {
          return (
               <Editor
                         initialValue={ this.props.initialValue}
                         init={this.editorConfig}
                         onChange = { (e) => this.props.contentChanged(e.target.getContent())}
                         onBlur = { (event) => this.props.onBlur ? this.props.onBlur(event) : true }
                    />
          );
     }
}
`

I have also attached my package.json file 

`{  
   "name":"closing-checklist",
   "version":"0.0.1",
   "private":true,
   "engines":{  
      "node":">=0.10.0"
   },
   "scripts":{  
      "build":"gulp bundle",
      "clean":"gulp clean",
      "test":"gulp test"
   },
   "dependencies":{  
      "@microsoft/sp-core-library":"~1.4.1",
      "@microsoft/sp-lodash-subset":"~1.4.1",
      "@microsoft/sp-office-ui-fabric-core":"~1.4.1",
      "@microsoft/sp-property-pane":"~1.5.0",
      "@microsoft/sp-webpart-base":"~1.4.1",
      "@pnp/spfx-property-controls":"^1.16.0",
      "@tinymce/tinymce-react":"^2.1.4",
      "@types/es6-promise":"0.0.33",
      "@types/react":"15.6.6",
      "@types/react-dom":"15.5.6",
      "@types/webpack-env":">=1.12.1 <1.14.0",
      "file-saver":"^2.0.2",
      "fs-finder":"^1.8.1",
      "gulp-spsync-creds":"^2.3.8",
      "hjson":"^3.1.2",
      "jszip":"^3.2.2",
      "jszip-utils":"^0.1.0",
      "node-sppkg-deploy":"^1.2.1",
      "office-ui-fabric-react":"6.143.0",
      "office-ui-fabric-react-pagination":"0.0.8",
      "react":"15.6.2",
      "react-dom":"15.6.2",
      "react-beautiful-dnd":"^11.0.4",
      "react-collapsible":"^2.6.0",
      "react-device-detect":"^1.7.5",
      "sp-pnp-js":"^3.0.10",
      "tinymce":"^4.7.6"
   },
   "resolutions":{  
      "@types/react":"16.7.22"
   },
   "devDependencies":{  
      "@microsoft/rush-stack-compiler-2.9":"0.7.7",
      "@microsoft/sp-build-web":"~1.4.1",
      "@microsoft/sp-module-interfaces":"~1.4.1",
      "@microsoft/sp-tslint-rules":"~1.4.1",
      "@microsoft/sp-webpart-workbench":"~1.4.1",
      "@types/chai":"3.4.34",
      "@types/file-saver":"^2.0.1",
      "@types/mocha":"2.2.38",
      "ajv":"~5.2.2",
      "gulp":"~3.9.1"
   }
}`
The text color and background color should be shown like this 

![image](https://user-images.githubusercontent.com/21018485/62516148-e1ab5d80-b841-11e9-9bac-2de9c22edf9a.png)

Even if use the latest versions 
**Tinymce version: 5.0.13
tinymce/tinymce-react: 3.3.0**
 it's not working and the colors are not shown for the text as well as background

**Comment by SimonFc** [comment] 2019-08-12 07:56
Hi @suryarsp I'm not sure if I understand what the issue is, are you able to reproduce it [here](https://codesandbox.io/s/tinymcereact-x8v9i)?

**Comment by suryarsp** [comment] 2019-08-13 09:23
> Hi @suryarsp I'm not sure if I understand what the issue is, are you able to reproduce it 
[https://codesandbox.io/s/tinymcereact-346ib?fontsize=14](url)
It works correctly on reactDom render but if I use it component render method it is not working

**Comment by SimonFc** [comment] 2019-08-13 11:17
So you're unable to reproduce the issue on Codesandbox? You could make a GitHub repo as well, or a more detailed explanation here, just something that describes the issue.

**Comment by suryarsp** [comment] 2019-08-13 13:27
Let say we have two components namely A & B. 
A has the Editor component referred in Render method. Component A is working fine individually. 
If we add component A inside component B then it breaks the additional features like text color,..etc

**Comment by SimonFc** [comment] 2019-08-13 15:47
I'm sure there is something more going on than simply having tinymce-react nested within two components. What's special about component B? You should be able to reproduce that on CodeSandbox.

I would like to help you(or fix a bug if there's one) but without a clear reproduction it's difficult!

**Comment by tiny-james** [comment] 2020-05-06 02:12
We need more information on this case to replicate the issue - preferably an example.

I will leave this case open for an additional 14 days, if no further example is provided I will close it.

**Comment by tinydylan** [comment] 2020-06-19 01:03
Hi,

This case has now been closed. If the issue persists, can you please provide some more information to help us diagnose and we'll be happy to investigate further.

**Closed by tinydylan** 2020-06-19 01:03 UTC
Labels: need information
